### PR TITLE
Add support to php 8.0

### PR DESCRIPTION
**Pull request by leopoletto**
I added support do php 8.0 in the composer.json file. Tested here and everything worked just fine.

### CODE REVIEW

**Comment by mattstauffer** [comment]
@leopoletto Unless I'm mistaken, there's no need for this, because the constraint is not `~`, it's `>=`. Is there something I don't know about here?

**Comment by leopoletto** [comment]
@mattstauffer my mistake. Actually the problem is the constraint  `"spatie/laravel-analytics": "^3.6".

The Spatie's package only introduced PHP 8 support in the version [4.0.0](https://github.com/spatie/laravel-analytics/releases/tag/4.0.0). But I am aware that it would not be possible to update it in the composer file since they also dropped support to PHP 7.x in this version.

Thank you.

**Comment by mattstauffer** [comment]
@leopoletto Hm, I wish they hadn't done that, but I think we can still make that bump, since we don't want to support PHP 7 *at the exclusion of PHP 8.*

I'd love a PR to bump that Spatie package constraint, and then make the PHP version minimum 8, if you would be up for it?

**Comment by leopoletto** [comment]
@mattstauffer sure, just sent another PR proposing the bump. 

Thank you!

**Pull request closed without merging**
